version: '3'

services:
  gift-list:
    env_file:
      - .env
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=giftlist_development