Family.create(name: 'McMahon')
Family.create(name: 'Tawaststjerna')

User.create(name: 'kevin', password: 'test')
User.create(name: 'andrew', password: 'test')
User.create(name: 'charlotte', password: 'test')
User.create(name: 'dale', password: 'test')
User.create(name: 'leonard', password: 'test')
User.create(name: 'heather', password: 'test')
User.create(name: 'darcy', password: 'test')

Family.find_by(name: 'McMahon').add_user_to_family(User.find_by(name: 'kevin'))
Family.find_by(name: 'McMahon').add_user_to_family(User.find_by(name: 'andrew'))
Family.find_by(name: 'McMahon').add_user_to_family(User.find_by(name: 'charlotte'))
Family.find_by(name: 'McMahon').add_user_to_family(User.find_by(name: 'dale'))

Family.find_by(name: 'Tawaststjerna').add_user_to_family(User.find_by(name: 'kevin'))
Family.find_by(name: 'Tawaststjerna').add_user_to_family(User.find_by(name: 'andrew'))
Family.find_by(name: 'Tawaststjerna').add_user_to_family(User.find_by(name: 'charlotte'))
Family.find_by(name: 'Tawaststjerna').add_user_to_family(User.find_by(name: 'leonard'))
Family.find_by(name: 'Tawaststjerna').add_user_to_family(User.find_by(name: 'heather'))
Family.find_by(name: 'Tawaststjerna').add_user_to_family(User.find_by(name: 'darcy'))